<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file has to live next to the docroot so WordPress can find it: WP only
 * looks in its own directory or one directory up for wp-config.php.
 */
require_once __DIR__ . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
