<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file has to live next to the docroot so WordPress can find it: WP only
 * looks in its own directory or one directory up for wp-config.php.
 */

/**
 * Docroot, passé explicitement à la configuration : sur le serveur, config/ est
 * atteint via un lien (website/config -> shared/config) et PHP résout __DIR__
 * vers le chemin RÉEL. Le calculer depuis application.php viserait shared/ au
 * lieu de website/.
 */
$lcds_webroot_dir = __DIR__;

/**
 * Emplacement de la configuration : dans le docroot sur le serveur (lien vers
 * shared/config), à la racine du dépôt en local. Pas de lien à créer en local.
 */
$lcds_config_dir = is_dir(__DIR__ . '/config') ? __DIR__ . '/config' : dirname(__DIR__) . '/config';

require_once __DIR__ . '/vendor/autoload.php';
require_once $lcds_config_dir . '/application.php';
require_once ABSPATH . 'wp-settings.php';
