<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file has to live next to the docroot so WordPress can find it: WP only
 * looks in its own directory or one directory up for wp-config.php.
 *
 * The docroot is passed explicitly to the configuration: config/ is reached
 * through a symlink on the server (website/config -> shared/config), and PHP
 * resolves __DIR__ to the REAL path — deriving the docroot from inside
 * application.php would land in shared/ instead of website/.
 */
$lcds_webroot_dir = __DIR__;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
